var welcome_text = "<p>Welcome to the experiment. This experiment should take no longer than 20 minutes.</p> <p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of 40 cue-target pairs, after which you will be given a memory test for the second word in each pair. For example, you may be asked to study the pair 'LINT - HINT', where LINT is the cue and HINT is the target. The cue and target will always rhyme. For a given cue-target pair, both cue and target will be four-letter words. There are two possible kinds of study trials: <br><br> On some of the trails, both the cue and target will be spelt out for you, e.g. LINT - HINT. When both the cue and target are spelt out your task will be to read both items to yourself. You will have 3 seconds to read the study pair. <br><br> On other trials, the cue will be spelt out, and only the first letter of the target will be shown, e.g. LINT - H_ _ _?. On these trials, your job is to generate the rhyming target word by typing, and then read the cue-target pair to yourself. You will again have 3 seconds to do this. <b>Typing is being recorded.</b><br><br>At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and takes approximately 15 minutes to complete. Also, when prompted to provide the answer, respond by typing in the answer to 2+2 = __. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p><p>Press any key to begin.</p>";

var post_practice_text = "<p>Remember! When you see only part of the second word appear (e.g. LINT - H_ _ _?) you must <b>TYPE the rest of the second word.</b> When you see the second word appear intact, your job will be to do nothing, and <b>simply READ that word silently.</b> Please only type or read the second word in each pair.</p>"+"<p>Typing is being recorded. Press 'w' to continue.</p>";


var attention_check_text = "Provide the answer:";

var fullscreen_prompt = "<p><b>Please turn off all background audio for the experiment</b>. Do not continue until you have turned off all other audio.</p>"+"<p>Also, remain in fullscreen mode for the entire experiment. The experiment will switch to full screen mode when you press the button below. It will also record if you exit fullscreen mode.</p>";

var debrief_text = "<p>In an elaborative processing experiment, participants are asked to study words that include some sort of elaborative processing, and some that do not. This form of elaborative processing can take on many forms, which include, but are not limited to, speaking words aloud, typing words, or trying to generate part of a word from an incomplete fragment or associated cue. When tested on recognition for these words, participants discriminate words that were studied in a training list from words that were not presented in the training list. Further, participants routinely have higher rates of recognition for words that were subjected to the elaborative processing manipulation than the words that were not (e.g. people remember words that they typed better than words that they just read). In conjunction with this, we are going to use a computational model of memory, called MINERVA 2, to derive predictions that are consistent with human performance. The ultimate goal of this research is to be able to derive predictions about elaborative processing that account for a number of related effects. You can learn more about this line of work from our laboratory webpage located at home.cc.umanitoba.ca/~jamiesor.</p><p>Press any key to finish the experiment.</p><br><p>Thank you for your help,<br>Jackie Spear<br>Ph.D. Student<br>Department of Psychology<br>University of Manitoba</p>";


var test_instruction_text = "<p>Take a rest if you need.</p>"+"<p>Next, your job will be to indicate whether you previously studied a word by pressing 'y', otherwise press 'n'. Keep your index fingers on these keys.</p>"+"<p>When you are ready press 'i' to continue.</p>";
